### ISSUE TITLE
1 Shot

### ISSUE THREAD

**Issue by SuperDude36** [Muqsit/ObsidianBreaker#1]
Even when I set the hardness to 49 obsidian is still a 1 shot with tnt. Is there anyway I can make it so obsidian takes like 4 hits?

**Comment by Muqsit** [comment]
I've already fixed this but don't want to publicly release the plugin. You can test it on my server.

**Comment by SuperDude36** [comment]
And that is...

**Comment by SuperDude36** [comment]
Like RamBunCraft?

**Comment by Muqsit** [comment]
CosmicPE

**Comment by SuperDude36** [comment]
Ohhhh, how do you do your custom enchants? Just a tiny little hint? I'm guessing custom server software.

**Comment by CREEPERBOYGAMINGXoticRealmsDev** [comment]
I had to make a new account and I think I got ip banned from cosmic idk why and I am blubbers friend. I need this plugin can u plz contact me at xoticrealmshelp@gmail.com   the fixed plugin

**Comment by CREEPERBOYGAMINGXoticRealmsDev** [comment]
cuz blubbers wifi wont be on for like 20 weeks I talked to him on kikk today

**Comment by CREEPERBOYGAMINGXoticRealmsDev** [comment]
kik

**Comment by Shock95** [comment]
@SuperDude36 Not really a custom server software, just editing Enchantments.php from Genisys, but you must have a CE plugin

**Comment by ghost** [comment]
I have a CE plugin

**Comment by ghost** [comment]
lmao

**Comment by Shock95** [comment]
Same

**Comment by ghost** [comment]
use nbt tags and ExplosionPrimeEvent to check how many lives left it got

**Comment by ghost** [comment]
ByteTag, CompoundTag

**Comment by SuperDude36** [comment]
Umm, like I know what half of that is. All I do is copy and paste stuff and edit messages and items. That's it. Don't speak PHP or pocketmine-ish to me...

**Comment by ghost** [comment]
@SuperDude36 so?

**Comment by Shock95** [comment]
@SuperDude36 ???

**Comment by SuperDude36** [comment]
I don't understand PHP so don't tell me stuff

**Comment by ghost** [comment]
@SuperDude36 I don't care

**Comment by SuperDude36** [comment]
Um ok, lol. What did you have for lunch yesterday?

**Comment by ghost** [comment]
@SuperDude36 hmm, lemme think... oh its bananas!

**Comment by SuperDude36** [comment]
@KairusDarkSeeker Nice! I love bananas!!!

**Comment by ghost** [comment]
@SuperDude36 lol
